services:
  # AWS (localstack) container
  # https://hub.docker.com/r/localstack/localstack
  aws:
    container_name: localenv-container-aws
    image: localstack/localstack:3.2.0-amd64
    platform: linux/amd64
    environment:
      LANG: C.UTF-8
      TZ: Z
      # EAGER_SERVICE_LOADING: "1"
      # SERVICES: dynamodb,kms,s3
      # DEBUG: 1
      AWS_ENDPOINT_URL: http://localhost:4566
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_DEFAULT_REGION: ap-northeast-1
    networks:
      - default
    ports:
      - 4566:4566
    volumes:
      - ./docker/aws/init/ready.d:/etc/localstack/init/ready.d:ro
      - ./docker/aws/init/keys:/init/keys:rw

  # DB (MySQL/MariaDB) container
  # https://hub.docker.com/_/mysql
  # https://hub.docker.com/_/mariadb
  db:
    container_name: localenv-container-db
    image: mysql:8.3.0-oraclelinux8
    # image: mariadb:11.3.2-jammy
    platform: linux/amd64
    environment:
      LANG: C.UTF-8
      TZ: Z
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: dbname
      MYSQL_USER: username
      MYSQL_PASSWORD: password
    networks:
      - default
    ports:
      - 3306:3306
    volumes:
      - ./docker/db/conf:/etc/mysql/conf.d:ro
      - ./docker/db/init:/docker-entrypoint-initdb.d:ro
      # - ./docker/db/logs:/var/log/mysql:rw
      # - ./docker/db/data:/var/lib/mysql:rw

  # MongoDB container
  # https://hub.docker.com/_/mongo
  mongo:
    container_name: localenv-container-mongo
    # image: mongo:7.0.7-jammy
    image: mongo:5.0.25-focal
    # image: mongo:4.4.29-focal
    platform: linux/amd64
    environment:
      LANG: C.UTF-8
      TZ: Z
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: test
    networks:
      - default
    ports:
      - 27017:27017
    volumes:
      - ./docker/mongo/init:/docker-entrypoint-initdb.d:ro

  # Redis container
  # https://hub.docker.com/_/redis
  # https://redis.io/topics/config
  redis:
    container_name: localenv-container-redis
    image: redis:7.2.4-bookworm
    platform: linux/amd64
    environment:
      LANG: C.UTF-8
      TZ: Z
    networks:
      - default
    ports:
      - 6379:6379
    # volumes:
    #   - ./docker/redis/conf:/etc/redis
    #   - ./docker/redis/data:/data:rw
    # command: [redis-server, /etc/redis/redis.conf]

  # Golang container
  # https://hub.docker.com/_/golang
  golang:
    container_name: localenv-container-golang
    image: golang:1.22.1-bullseye
    platform: linux/amd64
    environment:
      LANG: C.UTF-8
      TZ: Z
      AWS_ENDPOINT_URL: http://aws:4566
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_DEFAULT_REGION: ap-northeast-1
      DATABASE_DSN: "username:password@tcp(db:3306)/dbname?parseTime=true&loc=Asia%2FTokyo"
      MONGODB_URI: "mongodb://username:password@mongo:27017/test"
      REDIS_ADDR: "redis:6379"
    networks:
      - default
    volumes:
      - ./golang:/app:rw
    working_dir: /app
    tty: true

networks:
  default:
    name: localenv-network-default
