services:
  # AWS (localstack) container
  # https://hub.docker.com/r/localstack/localstack
  aws:
    container_name: localenv-container-aws
    image: localstack/localstack:2.2.0
    platform: linux/amd64
    environment:
      LANG: C.UTF-8
      TZ: Z
      # EAGER_SERVICE_LOADING: "1"
      # SERVICES: dynamodb,kms,s3
      # DEBUG: 1
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_DEFAULT_REGION: ap-northeast-1
    networks:
      - default
    ports:
      - 4566:4566
    volumes:
      - ./docker/aws/init/ready.d:/etc/localstack/init/ready.d:ro
      - ./docker/aws/init/keys:/init/keys:rw

  # DB (MySQL/MariaDB) container
  # https://hub.docker.com/_/mysql
  # https://hub.docker.com/_/mariadb
  db:
    container_name: localenv-container-db
    image: mysql:8.1.0
    # image: mariadb:11.1.2-jammy
    platform: linux/amd64
    environment:
      LANG: C.UTF-8
      TZ: Z
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: dbname
      MYSQL_USER: username
      MYSQL_PASSWORD: password
    networks:
      - default
    ports:
      - 3306:3306
    volumes:
      - ./docker/db/conf:/etc/mysql/conf.d:ro
      - ./docker/db/init:/docker-entrypoint-initdb.d:ro
      # - ./docker/db/logs:/var/log/mysql:rw
      # - ./docker/db/data:/var/lib/mysql:rw

  # MongoDB container
  # https://hub.docker.com/_/mongo
  mongo:
    container_name: localenv-container-mongo
    image: mongo:6.0.10-jammy
    platform: linux/amd64
    environment:
      LANG: C.UTF-8
      TZ: Z
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: test
    networks:
      - default
    ports:
      - 27017:27017
    volumes:
      - ./docker/mongo/init:/docker-entrypoint-initdb.d:ro
      - ./docker/mongo/data:/data/db:rw

  # Redis container
  # https://hub.docker.com/_/redis
  # https://redis.io/topics/config
  redis:
    container_name: localenv-container-redis
    image: redis:7.2.1-bookworm
    platform: linux/amd64
    environment:
      LANG: C.UTF-8
      TZ: Z
    networks:
      - default
    ports:
      - 6379:6379
    # volumes:
    #   - ./docker/redis/conf:/etc/redis
    #   - ./docker/redis/data:/data:rw
    # command: [redis-server, /etc/redis/redis.conf]

networks:
  default:
    name: localenv-network-default
